# Generated by Django 5.2.7 on 2025-10-29 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registrants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('sub_city', models.CharField(blank=True, max_length=100, null=True)),
                ('university', models.CharField(blank=True, max_length=255, null=True)),
                ('graduation_year', models.CharField(blank=True, max_length=10, null=True)),
                ('selected_course', models.CharField(choices=[('none', 'None'), ('marketing', 'Marketing'), ('ai', 'AI')], max_length=50)),
                ('marketing_experience', models.TextField(blank=True, null=True)),
                ('programming_experience', models.CharField(choices=[('none', 'None'), ('basic', 'Basic'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='none', max_length=20)),
                ('data_tools', models.CharField(choices=[('none', 'None'), ('excel', 'Excel'), ('python', 'Python'), ('r', 'R'), ('powerbi', 'Power BI')], default='none', max_length=20)),
                ('math_background', models.CharField(choices=[('none', 'None'), ('basic', 'Basic'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='none', max_length=20)),
                ('familiarity', models.JSONField(default=dict)),
                ('motivation', models.TextField(blank=True, null=True)),
                ('referral', models.CharField(blank=True, max_length=255, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event')),
                ('registrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to='registrants.registrant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('registrant', 'event'), name='unique_event_registration')],
            },
        ),
    ]
