# Generated by Django 5.2.7 on 2026-01-22 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('background', models.CharField(choices=[('engineer', 'Engineer'), ('educator', 'Educator'), ('healthcare', 'Healthcare'), ('finance', 'Finance'), ('it', 'IT'), ('other', 'Other')], max_length=50)),
                ('experience', models.CharField(choices=[('none', 'No experience'), ('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=50)),
                ('goals', models.TextField(blank=True)),
                ('referral', models.CharField(choices=[('social-media', 'Social Media'), ('friend', 'Friend'), ('search', 'Search Engine'), ('event', 'Event'), ('advertisement', 'Advertisement'), ('other', 'Other')], max_length=50)),
                ('agreed_terms', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
