# Generated by Django 5.2.7 on 2026-03-17 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customcourseenrollment',
            name='location',
            field=models.CharField(blank=True, choices=[('aastu', 'Addis Ababa Science and Technology University'), ('ict-park', 'ICT Park'), ('fdre-tvt', 'FDRE TVT Institute')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customcourseenrollment',
            name='mode',
            field=models.CharField(choices=[('online', 'Online'), ('hybrid', 'Hybrid'), ('in-person', 'In-Person')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
