# Generated by Django 5.2.7 on 2026-01-22 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_agreed_terms_customcourseenrollment_agreeterms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customcourseenrollment',
            old_name='agreeTerms',
            new_name='agreed_terms',
        ),
    ]
