# Generated by Django 5.2.7 on 2025-10-29 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_id_alter_eventregistration_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventregistration',
            name='email',
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='phone',
        ),
    ]
