# Generated by Django 5.2.7 on 2025-10-29 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_eventregistration_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='fieldOfStudy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
