# Generated by Django 5.2.7 on 2026-04-14 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_eventregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='attendance_type',
            field=models.CharField(blank=True, choices=[('in_person', 'In Person'), ('virtual', 'Virtual')], max_length=20, null=True),
        ),
    ]
