# Generated by Django 5.2.7 on 2025-10-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_eventregistration_fieldofstudy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='data_tools',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('excel', 'Excel'), ('python', 'Python'), ('r', 'R'), ('powerbi', 'Power BI')], default='none', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='math_background',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('basic', 'Basic'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='none', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='programming_experience',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('basic', 'Basic'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='none', max_length=20, null=True),
        ),
    ]
