# Generated by Django 5.2.7 on 2025-12-23 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_user_first_name_user_last_name_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moodle_course_id', models.PositiveIntegerField(help_text='ID of the course in Moodle')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_image', models.ImageField(help_text='Payment receipt image', upload_to='receipts/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('finance_approved', 'Finance Approved'), ('management_approved', 'Management Approved'), ('rejected', 'Rejected'), ('enrolled', 'Enrolled in Moodle')], default='pending', max_length=30)),
                ('finance_approved_at', models.DateTimeField(blank=True, null=True)),
                ('management_approved_at', models.DateTimeField(blank=True, null=True)),
                ('moodle_enrolled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='courses.course')),
                ('finance_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_approvals', to='users.staff')),
                ('management_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='management_approvals', to='users.staff')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_registrations', to='users.student')),
            ],
            options={
                'unique_together': {('student', 'course')},
            },
        ),
    ]
