# Generated by Django 5.2.7 on 2026-03-11 08:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moodle_course_id', models.PositiveIntegerField(help_text='ID of the course in Moodle')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_image', models.ImageField(help_text='Payment receipt image', upload_to='receipts/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('finance_approved', 'Finance Approved'), ('management_approved', 'Management Approved'), ('rejected', 'Rejected'), ('enrolled', 'Enrolled in Moodle')], default='pending', max_length=30)),
                ('prefered_format', models.CharField(choices=[('online', 'online'), ('inperson', 'inperson')], default='online', max_length=30)),
                ('prefered_start_date', models.DateTimeField(blank=True, null=True)),
                ('finance_approved_at', models.DateTimeField(blank=True, null=True)),
                ('management_approved_at', models.DateTimeField(blank=True, null=True)),
                ('moodle_enrolled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='courses.course')),
            ],
        ),
    ]
