# Generated by Django 5.2.7 on 2025-12-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseregistration',
            name='prefered_format',
            field=models.CharField(choices=[('online', 'online'), ('inperson', 'inperson')], default='online', max_length=30),
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='prefered_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
