# Generated by Django 5.2.7 on 2025-12-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_courseregistration_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseregistration',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
