# Generated by Django 5.2.7 on 2025-12-25 09:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_courseregistration_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseregistration',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
