# Generated by Django 5.2.7 on 2026-07-06 08:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BootcampRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('prefer_not_to_say', 'Prefer not to say'), ('other', 'Other')], max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('area_of_residence', models.CharField(help_text='Area or sub-city within Addis Ababa', max_length=150)),
                ('applicant_type', models.CharField(choices=[('university_student', 'University Student'), ('recent_graduate', 'Recent Graduate'), ('high_school_student', 'High School Student'), ('other', 'Other')], max_length=30)),
                ('school_university_company', models.CharField(help_text='Name of school, university, or company', max_length=255)),
                ('field_role', models.CharField(help_text='Field of study, grade level, or job title depending on applicant type', max_length=255)),
                ('role', models.CharField(choices=[('technical', 'Technical / Builder'), ('non_technical', 'Non-Technical / Launcher'), ('not_sure', 'Not Sure — Let ADITA Assign')], help_text='Technical/Builder, Non-Technical/Launcher, or Not Sure', max_length=20)),
                ('motivation', models.TextField(help_text='Why do you want to join Build the Product? (2–3 sentences)')),
                ('ai_experience', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], help_text='Have you used any AI tools before?', max_length=5)),
                ('ai_tools_used', models.TextField(blank=True, help_text='Which AI tools? What did you use them for? (leave blank if none)')),
                ('referral', models.CharField(choices=[('social_media', 'Social Media (LinkedIn, Telegram, TikTok, Instagram)'), ('friend_classmate', 'Friend or Classmate'), ('university_notice', 'University / Department Notice'), ('adita_event', 'ADITA Event or Seminar'), ('advertisement', 'Advertisement'), ('other', 'Other')], max_length=30)),
                ('guardian_name', models.CharField(blank=True, help_text='Required for applicants under 18', max_length=150)),
                ('guardian_phone', models.CharField(blank=True, help_text='Required for applicants under 18', max_length=20)),
                ('guardian_consent', models.BooleanField(default=False, help_text='Parent/guardian has approved participation')),
                ('agreed_terms', models.BooleanField(default=False)),
                ('agreed_photo_consent', models.BooleanField(default=False)),
                ('agreed_data_policy', models.BooleanField(default=False)),
                ('agreed_attendance_commitment', models.BooleanField(default=False)),
                ('agreed_employer_referral', models.BooleanField(default=False, help_text='Optional — consent for ADITA to share profile with employers')),
                ('payment_receipt', models.ImageField(help_text='Screenshot or scan of payment receipt', upload_to='bootcamp_receipts/')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending Review'), ('confirmed', 'Payment Confirmed'), ('rejected', 'Payment Rejected'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('payment_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('payment_notes', models.TextField(blank=True, help_text='Internal notes on payment (admin use)')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bootcamp Registration',
                'verbose_name_plural': 'Bootcamp Registrations',
                'ordering': ['-registered_at'],
            },
        ),
    ]
