# Generated by Django 5.2.7 on 2025-12-25 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_first_name_user_last_name_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('manager', 'manager'), ('hr', 'hr'), ('support', 'support'), ('finance', 'finance')], max_length=10),
        ),
    ]
