# Generated by Django 5.2.7 on 2025-12-29 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_staff_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='moodle_user_id',
            field=models.PositiveIntegerField(blank=True, help_text='User ID in Moodle', null=True),
        ),
    ]
